name: ubuntu

on:
  workflow_dispatch:
  push:
    paths:
      - '**'
      - '!.github/**'
      - '.github/workflows/ubuntu.yml'
      - '!**.md'
  pull_request:
    paths:
      - '**'
      - '!.github/**'
      - '.github/workflows/ubuntu.yml'
      - '!**.md'

jobs:
  linux:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        options: ['', '-DASSISTANTLIB_WITH_OPENSSL=OFF']

    steps:

    - name: Checkout assistant
      uses: actions/checkout@v6
      with:
        submodules: 'true'

    - name: cmake --version
      run: cmake --version

    - name: Build and Test
      run: |
        mkdir build-release
        cd build-release
        cmake .. -DCMAKE_BUILD_TYPE=Release -DASSISTANTLIB_BUILD_TESTS=ON ${{ matrix.options }}
        cmake --build . --config Release --parallel $(nproc)
        tests/test_claude_response_parser
