name: windows

on:
  workflow_dispatch:
  push:
    paths:
      - '**'
      - '!.github/**'
      - '.github/workflows/windows.yml'
      - '!**.md'
  pull_request:
    paths:
      - '**'
      - '!.github/**'
      - '.github/workflows/windows.yml'
      - '!**.md'

jobs:
  windows:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        options: ['', '-DASSISTANTLIB_WITH_OPENSSL=OFF']

    steps:

    - name: Checkout assistant
      uses: actions/checkout@v5

    - name: cmake --version
      run: cmake --version

    - name: Build
      run: |
        mkdir build-release
        cd build-release
        cmake .. -DCMAKE_BUILD_TYPE=Release ${{ matrix.options }}
        cmake --build . --config Release --parallel $(nproc)
